### ISSUE TITLE
'make' error

### ISSUE THREAD

**Issue by LeeNicha** [rsemeraro/XomeBlender#1]
Hi, I got nothing when I type 'make'.
Thank you in advance for your kind response.

**Comment by rsemeraro** [comment]
Hi,
do you have g++ on your machine?

**Comment by LeeNicha** [comment]
yes. I have g++.

**Comment by rsemeraro** [comment]
OK, if you go to Scripts folder how many scripts you find?

**Comment by LeeNicha** [comment]
3 files: ChrSizCentr.Rdata  Intervals_generator.R  SubCloneGenerator.R

**Comment by rsemeraro** [comment]
Ok, it didn't worked. If you type make it starts and never ends?

**Comment by LeeNicha** [comment]
Yes!!

**Comment by rsemeraro** [comment]
Ok, probably it can't find one or more dependencies. We can bypass it, if all dependencies are on your machine. (picard, GenomeAnalysisTK.jar, vcftools)

**Comment by LeeNicha** [comment]
I have all dependencies. What next should I do?

**Comment by rsemeraro** [comment]
ok, prepare a deps.txt file containing the paths to the executable of each dependency, in the order: 
/path/to/picard-tools-1.129/picard.jar
/path/to/GenomeAnalysisTK.jar
/path/to/vcftools_0.1.12b/cpp/vcftools

put this file in the Xome-Blender folder

Next, open the Makefile with a text editor and comment with # the first three lines in the file and the last three in the all block: $(PICARD_CHECK) $(PICARD_CHECK) $(VCFTOOLS_CHECK).
Save, type make and it should work!

**Comment by LeeNicha** [comment]
It has another error!
![screen shot 2561-04-12 at 17 28 29](https://user-images.githubusercontent.com/24719780/38672109-71d85a48-3e77-11e8-8ced-56431401f580.png)

**Comment by rsemeraro** [comment]
ok, if you type 'locate libm.a' what do you get?

**Comment by LeeNicha** [comment]
I got nothing.

**Comment by rsemeraro** [comment]
ok, you need the glibc-static library. If yum is on your system, you can install it by typing :yum install glibc-static

**Comment by LeeNicha** [comment]
ok. I type make and check the Scripts folder. It has 4 new files.
![screen shot 2561-04-12 at 17 57 56](https://user-images.githubusercontent.com/24719780/38673302-220baa16-3e7b-11e8-8019-f9ab2e1ed71e.png)

**Comment by LeeNicha** [comment]
I got following error with this command 'sh InXalizer.sh'.

![screen shot 2561-04-12 at 18 07 32](https://user-images.githubusercontent.com/24719780/38673790-7d2efbf4-3e7c-11e8-926d-adfd5431b313.png)

**Comment by rsemeraro** [comment]
try with 'bash ./InXalizer.sh'

**Comment by LeeNicha** [comment]
Thank you so much ^^.
