### ISSUE TITLE
setup question

### ISSUE THREAD

**Issue by ranneal** [rsemeraro/XomeBlender#2]
Hi, I got an error when I set-up:

rpy2 is no longer supporting Python < 3.5.Consider using an older rpy2 release when using an older Python release.
error: Setup script exited with 1

Is that mean I need python3.5 to run your package or I need to download the rpy2 module by myself on python2.7 with older release?

Cheers

**Comment by rsemeraro** [comment]
Hi, thanks for the suggestion. 
I managed this issue by adding a version upper limit for rpy2.
Clone the new XomeBlender folder and the problem should be fixed.
In addition, i am considering to adapt XomeBlender to python 3 version. But i don't have a lot of time, for the moment.

**Comment by ofonov** [comment]
refcheck() needs to be updated. It returns error for current versions of samtools 1.10 and bcftools 1.10.2
``
def refcheck():
    for r in ['samtools', 'bcftools']:
        tv = float(check_output([r, '--version']).split()[1])
        if tv < 1.6:
            log.error('The version of %s must be 1.6 or above.' % r)
``

**Comment by rsemeraro** [comment]
Hi,
Thanks for the suggestion I’m working on a new xome blender distribution and this problem is fixed. It will work also on python3 based systems. 
Stay tuned!

Roberto

**Comment by rsemeraro** [comment]
Hi, i just released a new version of Xome Blender  compatible with python3. Look for branch 3.1 and enjoy!
