### ISSUE TITLE
refcheck function needs to be updated

### ISSUE THREAD

**Issue by ofonov** [rsemeraro/XomeBlender#3]
refcheck() needs to be updated. It returns error for current versions of samtools 1.10 and bcftools 1.10.2

def refcheck():
for r in ['samtools', 'bcftools']:
tv = float(check_output([r, '--version']).split()[1])
if tv < 1.6:
log.error('The version of %s must be 1.6 or above.' % r)

**Comment by rsemeraro** [comment]
Hi,
Thanks for the suggestion I’m working on a new xome blender distribution and this problem is fixed. It will work also on python3 based systems.
Stay tuned!

**Comment by ofonov** [comment]
Great! Thank you for keeping the tool updated!

**Comment by rsemeraro** [comment]
Hi, i fixed the problem and released a new version of Xome Blender. Look for branch 3.1. The new version is for python3.
